services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: temp-file-host:${TAG:-latest}
    container_name: temp-file-host
    ports:
      - "11457:11457"
    volumes:
      - ./config/app_config.toml:/app/config/app_config.toml
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://0.0.0.0:11457/health"]
      interval: 30s
      timeout: 10s
      retries: 3 
