version: '3.8'

services:
  temp-file-host:
    build:
      context: ..
      dockerfile: temp-file-host/Dockerfile
    image: temp-file-host:${TAG:-latest}
    container_name: temp-file-host
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - APP_CONFIG_PATH=/app/config/sample.toml
    volumes:
      - temp-uploads:/app/uploads
      - ./config:/app/config:ro
    restart: unless-stopped
    networks:
      - temp-file-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  temp-file-network:
    driver: bridge

volumes:
  temp-uploads: 
