version: '3.8'

services:
  repo-host:
    build:
      context: ..
      dockerfile: repo-host/Dockerfile
    image: repo-host:${TAG:-latest}
    container_name: repo-host
    ports:
      - "8000:8000"
    environment:
      - RUST_LOG=info
    volumes:
      - repo-data:/app/data
      - repo-repos:/app/repos
      - ./keys:/app/keys:ro
    restart: unless-stopped
    networks:
      - repo-host-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  repo-host-network:
    driver: bridge

volumes:
  repo-data:
  repo-repos:
